# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650.git
          kernel-dir: android_kernel_oneplus_sm8650
          kernel-branch:  android_kernel_oneplus_sm8650
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          anykernel3: true
